### ISSUE TITLE
`import partd` fails if run in a location where `log` exists and is a directory

### ISSUE THREAD

**Issue by del82** [dask/partd#17]
If the current working directory is one in which the path `log` already exists and is a directory, `import partd` fails:

```
$ ls -l
total 0
drwxr-xr-x  2 somebody  wheel  68 Oct 14 11:48 log
$ python
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import partd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/anaconda3/lib/python3.5/site-packages/partd/__init__.py", line 16, in <module>
    from .zmq import Client, Server
  File "/path/to/anaconda3/lib/python3.5/site-packages/partd/zmq.py", line 33, in <module>
    log('Import zmq')
  File "/path/to/anaconda3/lib/python3.5/site-packages/partd/zmq.py", line 29, in log
    with open('log', 'a') as f:
IsADirectoryError: [Errno 21] Is a directory: 'log'
```

**Comment by rhunwicks** [comment]
This is also affecting us.
