### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by sciunto** [dask/partd#5]
Hi,

```
 % pew mktmpenv
Using base prefix '/usr'
New python executable in /home/fr/.local/share/virtualenvs/e5ecf64498bb9ee/bin/python3
Also creating executable in /home/fr/.local/share/virtualenvs/e5ecf64498bb9ee/bin/python
Installing setuptools, pip, wheel...done.
This is a temporary environment. It will be deleted when you exit
Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.
 % pip install partd
Collecting partd
Collecting locket (from partd)
Installing collected packages: locket, partd
Successfully installed locket-0.2.0 partd-0.3.2
 % python -c 'import partd'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fr/.local/share/virtualenvs/e5ecf64498bb9ee/lib/python3.5/site-packages/partd/__init__.py", line 3, in <module>
    from .file import File
  File "/home/fr/.local/share/virtualenvs/e5ecf64498bb9ee/lib/python3.5/site-packages/partd/file.py", line 3, in <module>
    from .core import Interface
  File "/home/fr/.local/share/virtualenvs/e5ecf64498bb9ee/lib/python3.5/site-packages/partd/core.py", line 7, in <module>
    from toolz import memoize
ImportError: No module named 'toolz'
```

and after I install toolz, pandas is missing.

With toolz and pandas, the import goes well.

**Comment by MaxPowerWasTaken** [comment]
I got a `ImportError: No module named 'partd'` running `my_dd = my_dd.set_index('PropertyID').compute()`, fixed after `pip install `partd`.
I also had to pip install toolz after installing dask as well.

I'm using dask 0.17.

**Comment by mrocklin** [comment]
See http://dask.pydata.org/en/latest/install.html#pip .  You probably wanted to `pip install dask[dataframe]`
